//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MauiApp1.Resources.Strings.tr {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MauiApp1.Resources.Strings.tr.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapat.
        /// </summary>
        public static string LanguageListPopupCloseBtn {
            get {
                return ResourceManager.GetString("LanguageListPopupCloseBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bir dil seç.
        /// </summary>
        public static string LanguageListPopupTitle {
            get {
                return ResourceManager.GetString("LanguageListPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        public static string NavBarAddBtn {
            get {
                return ResourceManager.GetString("NavBarAddBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Sayfa.
        /// </summary>
        public static string NavBarHomeBtn {
            get {
                return ResourceManager.GetString("NavBarHomeBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçenekler.
        /// </summary>
        public static string NavBarOptionsBtn {
            get {
                return ResourceManager.GetString("NavBarOptionsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kazandıranlar.
        /// </summary>
        public static string NavBarPerformersBtn {
            get {
                return ResourceManager.GetString("NavBarPerformersBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum.
        /// </summary>
        public static string NavBarStatusBtn {
            get {
                return ResourceManager.GetString("NavBarStatusBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para Birimi.
        /// </summary>
        public static string OptionsCurrencyMenu {
            get {
                return ResourceManager.GetString("OptionsCurrencyMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil.
        /// </summary>
        public static string OptionsLanguageMenu {
            get {
                return ResourceManager.GetString("OptionsLanguageMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İngilizce.
        /// </summary>
        public static string OptionsLanguagesEN {
            get {
                return ResourceManager.GetString("OptionsLanguagesEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkçe.
        /// </summary>
        public static string OptionsLanguagesTR {
            get {
                return ResourceManager.GetString("OptionsLanguagesTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildirimler.
        /// </summary>
        public static string OptionsNotificationMenu {
            get {
                return ResourceManager.GetString("OptionsNotificationMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrol Ediliyor.
        /// </summary>
        public static string OptionsNotificationsChecking {
            get {
                return ResourceManager.GetString("OptionsNotificationsChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reddedildi.
        /// </summary>
        public static string OptionsNotificationsDisabled {
            get {
                return ResourceManager.GetString("OptionsNotificationsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İzin Verildi.
        /// </summary>
        public static string OptionsNotificationsEnabled {
            get {
                return ResourceManager.GetString("OptionsNotificationsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapat.
        /// </summary>
        public static string PortfolioListPopupCloseBtn {
            get {
                return ResourceManager.GetString("PortfolioListPopupCloseBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni bir portfolyo yarat.
        /// </summary>
        public static string PortfolioListPopupCreateBtn {
            get {
                return ResourceManager.GetString("PortfolioListPopupCreateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bir portfolyo seç.
        /// </summary>
        public static string PortfolioListPopupTitle {
            get {
                return ResourceManager.GetString("PortfolioListPopupTitle", resourceCulture);
            }
        }
    }
}
