//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MauiApp1.Resources.Strings.en {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MauiApp1.Resources.Strings.en.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string AreYouSureTitle {
            get {
                return ResourceManager.GetString("AreYouSureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to change the language to %%1.
        /// </summary>
        public static string LanguageListPopupRestartMessage {
            get {
                return ResourceManager.GetString("LanguageListPopupRestartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a language.
        /// </summary>
        public static string LanguageListPopupTitle {
            get {
                return ResourceManager.GetString("LanguageListPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string MessageCANCEL {
            get {
                return ResourceManager.GetString("MessageCANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay.
        /// </summary>
        public static string MessageOK {
            get {
                return ResourceManager.GetString("MessageOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string NavBarAddBtn {
            get {
                return ResourceManager.GetString("NavBarAddBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string NavBarHomeBtn {
            get {
                return ResourceManager.GetString("NavBarHomeBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string NavBarOptionsBtn {
            get {
                return ResourceManager.GetString("NavBarOptionsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performers.
        /// </summary>
        public static string NavBarPerformersBtn {
            get {
                return ResourceManager.GetString("NavBarPerformersBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string NavBarStatusBtn {
            get {
                return ResourceManager.GetString("NavBarStatusBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string OptionsCurrencyMenu {
            get {
                return ResourceManager.GetString("OptionsCurrencyMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string OptionsLanguageMenu {
            get {
                return ResourceManager.GetString("OptionsLanguageMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string OptionsLanguagesEN {
            get {
                return ResourceManager.GetString("OptionsLanguagesEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish.
        /// </summary>
        public static string OptionsLanguagesTR {
            get {
                return ResourceManager.GetString("OptionsLanguagesTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string OptionsNotificationMenu {
            get {
                return ResourceManager.GetString("OptionsNotificationMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking.
        /// </summary>
        public static string OptionsNotificationsChecking {
            get {
                return ResourceManager.GetString("OptionsNotificationsChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification permission is required. Please enable it in the app settings..
        /// </summary>
        public static string OptionsNotificationsDeniedMessage {
            get {
                return ResourceManager.GetString("OptionsNotificationsDeniedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Denied.
        /// </summary>
        public static string OptionsNotificationsDeniedTitle {
            get {
                return ResourceManager.GetString("OptionsNotificationsDeniedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denied.
        /// </summary>
        public static string OptionsNotificationsDisabled {
            get {
                return ResourceManager.GetString("OptionsNotificationsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Granted.
        /// </summary>
        public static string OptionsNotificationsEnabled {
            get {
                return ResourceManager.GetString("OptionsNotificationsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Settings.
        /// </summary>
        public static string OptionsNotificationsGoToSettings {
            get {
                return ResourceManager.GetString("OptionsNotificationsGoToSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string PopupCloseBtn {
            get {
                return ResourceManager.GetString("PopupCloseBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new portfolio.
        /// </summary>
        public static string PortfolioListPopupCreateBtn {
            get {
                return ResourceManager.GetString("PortfolioListPopupCreateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a portfolio.
        /// </summary>
        public static string PortfolioListPopupTitle {
            get {
                return ResourceManager.GetString("PortfolioListPopupTitle", resourceCulture);
            }
        }
    }
}
